name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Who to greet
        options:
          - ""
          - "dm"
          - "mp"
          - "sp"
      take_disk_snapshot:
        type: boolean
        description: "Take a snapshot from the disk before removing it"
        required: true
      environment:
        required: true
        description: "env"

jobs:
  synatx_checkup:
    name: Scanning Environment Name
    runs-on: ubuntu-latest
    steps:
      - name: check length
        id: check_env_name
        run: |
          ns=${{ github.event.inputs.environment }}
          size=${#ns}
          echo $size
          if [[ ${{ github.event.inputs.environment }} == *['!'@#\$%^\&*()_+]* || $size -gt 15 ]]
          then
            echo "It contains one of those, and greater than 15"
          else
            echo "It is good"
          fi
  # greet:
  #   runs-on: ubuntu-latest
  #   needs: synatx_checkup
  #   steps:
  #     - name: Send greeting
  #       run:  echo "NAMESPACE=${{ github.event.inputs.team }}"-${{ github.event.inputs.name }}"
