name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Who to greet
        options:
          - ""
          - "dm"
          - "mp"
          - "sp"
      take_disk_snapshot:
        type: boolean
        description: "Take a snapshot from the disk before removing it"
        required: true
      environment:
        required: true
        description: "env"

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  synatx_checkup:
    name: Scanning Environment Name
    needs: build
    outputs:
      env_checks: ${{ steps.check_env_name.output.env_checks }}
    runs-on: ubuntu-latest
    steps:
      - name: check length
        id: check_env_name
        run: ./create_env.sh
        
        
  results:
    name: priniting output
    needs: synatx_checkup
    runs-on: ubuntu-latest
    steps:
      - name: printing output result
        run: echo "${{ needs.synatx_checkup.outputs.env_checks }}"
        
        
  # greet:
  #   runs-on: ubuntu-latest
  #   needs: synatx_checkup
  #   steps:
  #     - name: Send greeting
  #       run:  echo "NAMESPACE=${{ github.event.inputs.team }}"-${{ github.event.inputs.name }}"
