name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Who to greet
        options:
          - ""
          - "ct"
          - "dm"
          - "gt"
          - "mp"
          - "sp"
          - "sh"
      use-emoji:
        type: boolean
        description: "Include  emojis"
        required: false
      environment:
        required: false
        description: "env"

jobs:
  synatx_checkup:
    name: Scanning Environment Name
    runs-on: ubuntu-latest
    steps:
      - name: check length
        id: check_env_name
        run: |
          if [[ ${{ github.event.inputs.environment }} == *['!'@#\$%^\&*()_+]* ]]
          then
            echo "It contains one of those"
          else
            echo "It is good"
          fi
  # greet:
  #   runs-on: ubuntu-latest
  #   needs: synatx_checkup
  #   steps:
  #     - name: Send greeting
  #       run:  echo "NAMESPACE=${{ github.event.inputs.team }}"-${{ github.event.inputs.name }}"
